### ISSUE TITLE
Hitboxes do not match visuals

### ISSUE THREAD

**Issue by AJ-Ferguson** [Mshl2299/Ast-Emmental#6]
Hello. Nice work on this game, I really enjoy it. 
It would be nice if the hitboxes could be adjusted to better match their visuals. (I understand that the hitboxes are currently squares.) Here is a screenshot showing an example of the problem.

<img src="https://github.com/Mshl2299/Ast-Emmental/assets/7310330/5a086d3e-f127-4679-800c-46fa5c0edbf7" width="40%">

This was extracted from a video, showing the exact moment the game registered the collision.

**Comment by Mshl2299** [comment]
Updated (+ boosted scoring temporarily).
